name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build image
        run: |-
          docker login -u lusca33 -p $DOCKER_PASSWORD
          docker build \
            -t $DOCKER_USERNAME/pettech-stock:latest \
            --build-arg MONGO_URI=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            .

      - name: Push image
        run: |-
          docker push $DOCKER_USERNAME/pettech-stock:latest